//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.07 at 09:58:50 PM ICT 
//


package org.apache.pluto.container.om.portlet30.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 			The portlet element contains the declarative data of a portlet. 
 * 			Used in: portlet-app
 * 			
 * 
 * <p>Java class for portletType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="portletType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="description" type="{http://xmlns.jcp.org/xml/ns/portlet}descriptionType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="portlet-name" type="{http://xmlns.jcp.org/xml/ns/portlet}portlet-nameType"/&gt;
 *         &lt;element name="display-name" type="{http://xmlns.jcp.org/xml/ns/portlet}display-nameType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="portlet-class" type="{http://xmlns.jcp.org/xml/ns/portlet}portlet-classType" minOccurs="0"/&gt;
 *         &lt;element name="init-param" type="{http://xmlns.jcp.org/xml/ns/portlet}init-paramType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="expiration-cache" type="{http://xmlns.jcp.org/xml/ns/portlet}expiration-cacheType" minOccurs="0"/&gt;
 *         &lt;element name="cache-scope" type="{http://xmlns.jcp.org/xml/ns/portlet}cache-scopeType" minOccurs="0"/&gt;
 *         &lt;element name="supports" type="{http://xmlns.jcp.org/xml/ns/portlet}supportsType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="supported-locale" type="{http://xmlns.jcp.org/xml/ns/portlet}supported-localeType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="resource-bundle" type="{http://xmlns.jcp.org/xml/ns/portlet}resource-bundleType" minOccurs="0"/&gt;
 *         &lt;element name="portlet-info" type="{http://xmlns.jcp.org/xml/ns/portlet}portlet-infoType" minOccurs="0"/&gt;
 *         &lt;element name="portlet-preferences" type="{http://xmlns.jcp.org/xml/ns/portlet}portlet-preferencesType" minOccurs="0"/&gt;
 *         &lt;element name="security-role-ref" type="{http://xmlns.jcp.org/xml/ns/portlet}security-role-refType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="supported-processing-event" type="{http://xmlns.jcp.org/xml/ns/portlet}event-definition-referenceType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="supported-publishing-event" type="{http://xmlns.jcp.org/xml/ns/portlet}event-definition-referenceType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="supported-public-render-parameter" type="{http://xmlns.jcp.org/xml/ns/portlet}string" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="container-runtime-option" type="{http://xmlns.jcp.org/xml/ns/portlet}container-runtime-optionType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="dependency" type="{http://xmlns.jcp.org/xml/ns/portlet}dependencyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="async-supported" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="multipart-config" type="{http://xmlns.jcp.org/xml/ns/portlet}multipartType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://xmlns.jcp.org/xml/ns/portlet}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "portletType", propOrder = {
    "description",
    "portletName",
    "displayName",
    "portletClass",
    "initParam",
    "expirationCache",
    "cacheScope",
    "supports",
    "supportedLocale",
    "resourceBundle",
    "portletInfo",
    "portletPreferences",
    "securityRoleRef",
    "supportedProcessingEvent",
    "supportedPublishingEvent",
    "supportedPublicRenderParameter",
    "containerRuntimeOption",
    "dependency",
    "asyncSupported",
    "multipartConfig"
})
public class PortletType {

    protected List<DescriptionType> description;
    @XmlElement(name = "portlet-name", required = true)
    protected PortletNameType portletName;
    @XmlElement(name = "display-name")
    protected List<DisplayNameType> displayName;
    @XmlElement(name = "portlet-class")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String portletClass;
    @XmlElement(name = "init-param")
    protected List<InitParamType> initParam;
    @XmlElement(name = "expiration-cache")
    protected ExpirationCacheType expirationCache;
    @XmlElement(name = "cache-scope")
    protected CacheScopeType cacheScope;
    @XmlElement(required = true)
    protected List<SupportsType> supports;
    @XmlElement(name = "supported-locale")
    protected List<SupportedLocaleType> supportedLocale;
    @XmlElement(name = "resource-bundle")
    protected ResourceBundleType resourceBundle;
    @XmlElement(name = "portlet-info")
    protected PortletInfoType portletInfo;
    @XmlElement(name = "portlet-preferences")
    protected PortletPreferencesType portletPreferences;
    @XmlElement(name = "security-role-ref")
    protected List<SecurityRoleRefType> securityRoleRef;
    @XmlElement(name = "supported-processing-event")
    protected List<EventDefinitionReferenceType> supportedProcessingEvent;
    @XmlElement(name = "supported-publishing-event")
    protected List<EventDefinitionReferenceType> supportedPublishingEvent;
    @XmlElement(name = "supported-public-render-parameter")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected List<String> supportedPublicRenderParameter;
    @XmlElement(name = "container-runtime-option")
    protected List<ContainerRuntimeOptionType> containerRuntimeOption;
    protected List<DependencyType> dependency;
    @XmlElement(name = "async-supported")
    protected Boolean asyncSupported;
    @XmlElement(name = "multipart-config")
    protected MultipartType multipartConfig;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;

    /**
     * Gets the value of the description property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the description property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptionType }
     * 
     * 
     */
    public List<DescriptionType> getDescription() {
        if (description == null) {
            description = new ArrayList<DescriptionType>();
        }
        return this.description;
    }

    /**
     * Gets the value of the portletName property.
     * 
     * @return
     *     possible object is
     *     {@link PortletNameType }
     *     
     */
    public PortletNameType getPortletName() {
        return portletName;
    }

    /**
     * Sets the value of the portletName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortletNameType }
     *     
     */
    public void setPortletName(PortletNameType value) {
        this.portletName = value;
    }

    /**
     * Gets the value of the displayName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the displayName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDisplayName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DisplayNameType }
     * 
     * 
     */
    public List<DisplayNameType> getDisplayName() {
        if (displayName == null) {
            displayName = new ArrayList<DisplayNameType>();
        }
        return this.displayName;
    }

    /**
     * Gets the value of the portletClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortletClass() {
        return portletClass;
    }

    /**
     * Sets the value of the portletClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortletClass(String value) {
        this.portletClass = value;
    }

    /**
     * Gets the value of the initParam property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the initParam property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInitParam().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InitParamType }
     * 
     * 
     */
    public List<InitParamType> getInitParam() {
        if (initParam == null) {
            initParam = new ArrayList<InitParamType>();
        }
        return this.initParam;
    }

    /**
     * Gets the value of the expirationCache property.
     * 
     * @return
     *     possible object is
     *     {@link ExpirationCacheType }
     *     
     */
    public ExpirationCacheType getExpirationCache() {
        return expirationCache;
    }

    /**
     * Sets the value of the expirationCache property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExpirationCacheType }
     *     
     */
    public void setExpirationCache(ExpirationCacheType value) {
        this.expirationCache = value;
    }

    /**
     * Gets the value of the cacheScope property.
     * 
     * @return
     *     possible object is
     *     {@link CacheScopeType }
     *     
     */
    public CacheScopeType getCacheScope() {
        return cacheScope;
    }

    /**
     * Sets the value of the cacheScope property.
     * 
     * @param value
     *     allowed object is
     *     {@link CacheScopeType }
     *     
     */
    public void setCacheScope(CacheScopeType value) {
        this.cacheScope = value;
    }

    /**
     * Gets the value of the supports property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supports property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupports().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportsType }
     * 
     * 
     */
    public List<SupportsType> getSupports() {
        if (supports == null) {
            supports = new ArrayList<SupportsType>();
        }
        return this.supports;
    }

    /**
     * Gets the value of the supportedLocale property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedLocale property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedLocale().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SupportedLocaleType }
     * 
     * 
     */
    public List<SupportedLocaleType> getSupportedLocale() {
        if (supportedLocale == null) {
            supportedLocale = new ArrayList<SupportedLocaleType>();
        }
        return this.supportedLocale;
    }

    /**
     * Gets the value of the resourceBundle property.
     * 
     * @return
     *     possible object is
     *     {@link ResourceBundleType }
     *     
     */
    public ResourceBundleType getResourceBundle() {
        return resourceBundle;
    }

    /**
     * Sets the value of the resourceBundle property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResourceBundleType }
     *     
     */
    public void setResourceBundle(ResourceBundleType value) {
        this.resourceBundle = value;
    }

    /**
     * Gets the value of the portletInfo property.
     * 
     * @return
     *     possible object is
     *     {@link PortletInfoType }
     *     
     */
    public PortletInfoType getPortletInfo() {
        return portletInfo;
    }

    /**
     * Sets the value of the portletInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortletInfoType }
     *     
     */
    public void setPortletInfo(PortletInfoType value) {
        this.portletInfo = value;
    }

    /**
     * Gets the value of the portletPreferences property.
     * 
     * @return
     *     possible object is
     *     {@link PortletPreferencesType }
     *     
     */
    public PortletPreferencesType getPortletPreferences() {
        return portletPreferences;
    }

    /**
     * Sets the value of the portletPreferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortletPreferencesType }
     *     
     */
    public void setPortletPreferences(PortletPreferencesType value) {
        this.portletPreferences = value;
    }

    /**
     * Gets the value of the securityRoleRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the securityRoleRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecurityRoleRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SecurityRoleRefType }
     * 
     * 
     */
    public List<SecurityRoleRefType> getSecurityRoleRef() {
        if (securityRoleRef == null) {
            securityRoleRef = new ArrayList<SecurityRoleRefType>();
        }
        return this.securityRoleRef;
    }

    /**
     * Gets the value of the supportedProcessingEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedProcessingEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedProcessingEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventDefinitionReferenceType }
     * 
     * 
     */
    public List<EventDefinitionReferenceType> getSupportedProcessingEvent() {
        if (supportedProcessingEvent == null) {
            supportedProcessingEvent = new ArrayList<EventDefinitionReferenceType>();
        }
        return this.supportedProcessingEvent;
    }

    /**
     * Gets the value of the supportedPublishingEvent property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedPublishingEvent property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedPublishingEvent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventDefinitionReferenceType }
     * 
     * 
     */
    public List<EventDefinitionReferenceType> getSupportedPublishingEvent() {
        if (supportedPublishingEvent == null) {
            supportedPublishingEvent = new ArrayList<EventDefinitionReferenceType>();
        }
        return this.supportedPublishingEvent;
    }

    /**
     * Gets the value of the supportedPublicRenderParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedPublicRenderParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedPublicRenderParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSupportedPublicRenderParameter() {
        if (supportedPublicRenderParameter == null) {
            supportedPublicRenderParameter = new ArrayList<String>();
        }
        return this.supportedPublicRenderParameter;
    }

    /**
     * Gets the value of the containerRuntimeOption property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the containerRuntimeOption property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContainerRuntimeOption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContainerRuntimeOptionType }
     * 
     * 
     */
    public List<ContainerRuntimeOptionType> getContainerRuntimeOption() {
        if (containerRuntimeOption == null) {
            containerRuntimeOption = new ArrayList<ContainerRuntimeOptionType>();
        }
        return this.containerRuntimeOption;
    }

    /**
     * Gets the value of the dependency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dependency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDependency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DependencyType }
     * 
     * 
     */
    public List<DependencyType> getDependency() {
        if (dependency == null) {
            dependency = new ArrayList<DependencyType>();
        }
        return this.dependency;
    }

    /**
     * Gets the value of the asyncSupported property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAsyncSupported() {
        return asyncSupported;
    }

    /**
     * Sets the value of the asyncSupported property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAsyncSupported(Boolean value) {
        this.asyncSupported = value;
    }

    /**
     * Gets the value of the multipartConfig property.
     * 
     * @return
     *     possible object is
     *     {@link MultipartType }
     *     
     */
    public MultipartType getMultipartConfig() {
        return multipartConfig;
    }

    /**
     * Sets the value of the multipartConfig property.
     * 
     * @param value
     *     allowed object is
     *     {@link MultipartType }
     *     
     */
    public void setMultipartConfig(MultipartType value) {
        this.multipartConfig = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
