//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.03.07 at 09:58:50 PM ICT 
//


package org.apache.pluto.container.om.portlet30.impl;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 * 			Supports indicates the portlet modes a 
 * 			portlet supports for a specific content type. All portlets must 
 * 			support the view mode. 
 * 			Used in: portlet
 * 			
 * 
 * <p>Java class for supportsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="supportsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mime-type" type="{http://xmlns.jcp.org/xml/ns/portlet}mime-typeType"/&gt;
 *         &lt;element name="portlet-mode" type="{http://xmlns.jcp.org/xml/ns/portlet}portlet-modeType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="window-state" type="{http://xmlns.jcp.org/xml/ns/portlet}window-stateType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="id" type="{http://xmlns.jcp.org/xml/ns/portlet}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "supportsType", propOrder = {
    "mimeType",
    "portletMode",
    "windowState"
})
public class SupportsType {

    @XmlElement(name = "mime-type", required = true)
    protected MimeTypeType mimeType;
    @XmlElement(name = "portlet-mode")
    protected List<PortletModeType> portletMode;
    @XmlElement(name = "window-state")
    protected List<WindowStateType> windowState;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String id;

    /**
     * Gets the value of the mimeType property.
     * 
     * @return
     *     possible object is
     *     {@link MimeTypeType }
     *     
     */
    public MimeTypeType getMimeType() {
        return mimeType;
    }

    /**
     * Sets the value of the mimeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MimeTypeType }
     *     
     */
    public void setMimeType(MimeTypeType value) {
        this.mimeType = value;
    }

    /**
     * Gets the value of the portletMode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the portletMode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPortletMode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PortletModeType }
     * 
     * 
     */
    public List<PortletModeType> getPortletMode() {
        if (portletMode == null) {
            portletMode = new ArrayList<PortletModeType>();
        }
        return this.portletMode;
    }

    /**
     * Gets the value of the windowState property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the windowState property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWindowState().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WindowStateType }
     * 
     * 
     */
    public List<WindowStateType> getWindowState() {
        if (windowState == null) {
            windowState = new ArrayList<WindowStateType>();
        }
        return this.windowState;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

}
